# Lenguaje de programaci√≥n
language: python

# Versiones de python
python:
    - "3.6"
    - "3.6.8"
    - "3.7"
    - "3.8"

services:
    - mongodb

before_install:
    - pip install -r requirements.txt
    - pip install codecov

script:
    - invoke test
    - invoke coverage

after_success:
    - codecov
